<?php
$reportLanguage = [
    'en' => [
        ':language'   => 'English',
        'Account'     => 'Account',
        'Budget'      => 'Budget',
        'CostCenter'  => 'Cost Center',
        'CostObject'  => 'Cost Object',
        'Current'     => 'Current',
        'Date'        => 'Date',
        'Description' => 'Description',
        'Diff'        => 'Diff',
        'DiffPlan'    => 'Diff Plan %',
        'EventCourse' => 'Event Course',
        'Forecast'    => 'Forecast',
        'History'     => 'History',
        'ID'          => 'ID',
        'Name'        => 'Name',
        'Overview'    => 'Overview',
        'Plan'        => 'Plan',
        'Planning'    => 'Planning',
        'Progress'    => 'Progress',
        'Total'       => 'Total',
        'Type'        => 'Type',
    ],
];
