<?php
$reportLanguage = [
    'en' => [
        ':language'                     => 'English',
        'Account'                       => 'Account',
        'Actual'                        => 'Actual',
        'Actuals'                       => 'Actuals',
        'Budget'                        => 'Budget',
        'CostCenter'                    => 'Cost Center',
        'CostObject'                    => 'Cost Object',
        'CourseBudget'                  => 'Course Budget',
        'Current'                       => 'Current',
        'Cutoff'                        => 'Cutoff',
        'Date'                          => 'Date',
        'Description'                   => 'Description',
        'Diff'                          => 'Diff',
        'DiffBudget%'                   => 'Diff Budget %',
        'DiffHistory%'                  => 'Diff History %',
        'End'                           => 'End',
        'EventCourse'                   => 'Event Course',
        'FiscalYearEnd'                 => 'Fiscal Year End',
        'FiscalYearStart'               => 'Fiscal Year Start',
        'Forecast'                      => 'Forecast',
        'History'                       => 'History',
        'ID'                            => 'ID',
        'Name'                          => 'Name',
        'Overview'                      => 'Overview',
        'Pending'                       => 'Pending',
        'Plan'                          => 'Plan',
        'Planning'                      => 'Planning',
        'Progress'                      => 'Progress',
        'Remaining'                     => 'Remaining',
        'Start'                         => 'Start',
        'Total'                         => 'Total',
        'Type'                          => 'Type',
    ],
];
